In [3]:
# Import Dependencies
import pandas as pd

In [4]:
# Reference the file where the CSV is located
crime_csv_path = "Resources/crime_incident_data2017.csv"

# Import the data into a Pandas DataFrame
crime_df = pd.read_csv(crime_csv_path)

In [5]:
# look for missing values
crime_df.count()

Address              37365
Case Number          41032
Crime Against        41032
Neighborhood         39712
Number of Records    41032
Occur Date           41032
Occur Month Year     41032
Occur Time           41032
Offense Category     41032
Offense Count        41032
Offense Type         41032
Open Data Lat        36712
Open Data Lon        36712
Open Data X          36712
Open Data Y          36712
Report Date          41032
Report Month Year    41032
dtype: int64

In [20]:
# drop null rows
crime_df.dropna(how='any')

,Address,Case Number,Crime Against,Neighborhood,Number of Records,Occur Date,Occur Month Year,Occur Time,Offense Category,Offense Count,Offense Type,Open Data Lat,Open Data Lon,Open Data X,Open Data Y,Report Date,Report Month Year
2,200 BLOCK OF SE 78TH AVE,17-900367,Property,Montavilla,1,12/1/03,12/1/03,800,Fraud Offenses,1,False Pretenses/Swindle/Confidence Game,45.5207,-122.583,7668150.0,682825.0,1/9/17,1/1/17
5,5400 BLOCK OF NE MALLORY AVE,17-900129,Property,King,1,11/28/10,11/1/10,1612,Fraud Offenses,1,Identity Theft,45.5625,-122.664,7647987.0,698581.0,1/3/17,1/1/17
6,5000 BLOCK OF NE 19TH AVE,17-901079,Property,Vernon,1,11/8/13,11/1/13,1200,Fraud Offenses,1,False Pretenses/Swindle/Confidence Game,45.5594,-122.646,7652567.0,697337.0,1/26/17,1/1/17
7,5000 BLOCK OF NE 19TH AVE,17-901079,Property,Vernon,1,11/8/13,11/1/13,1200,Fraud Offenses,1,Identity Theft,45.5594,-122.646,7652567.0,697337.0,1/26/17,1/1/17
8,12000 BLOCK OF SE PINE ST,17-900253,Property,Hazelwood,1,1/6/14,1/1/14,805,Fraud Offenses,1,Credit Card/ATM Fraud,45.5204,-122.539,7679522.0,682404.0,1/6/17,1/1/17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41026,10200 BLOCK OF NE SANDY BLVD,17-286419,Society,Parkrose,1,8/31/17,8/1/17,2005,Drug/Narcotic Offenses,1,Drug/Narcotic Violations,45.5591,-122.557,7675224.0,696649.0,8/31/17,8/1/17
41027,8800 BLOCK OF NE SANDY BLVD,17-285386,Society,Sumner,1,8/31/17,8/1/17,535,Drug/Narcotic Offenses,1,Drug/Narcotic Violations,45.5554,-122.571,7671560.0,695399.0,8/31/17,8/1/17
41028,9700 BLOCK OF SE STARK ST,17-286082,Society,Hazelwood,1,8/31/17,8/1/17,1619,Prostitution Offenses,1,Prostitution,45.5191,-122.563,7673292.0,682101.0,8/31/17,8/1/17
41029,9700 BLOCK OF SE STARK ST,17-286413,Society,Hazelwood,1,8/31/17,8/1/17,1959,Prostitution Offenses,1,Prostitution,45.5191,-122.563,7673292.0,682101.0,8/31/17,8/1/17
41031,8000 BLOCK OF SE POWELL BLVD,17-286659,Society,Foster-Powell,1,8/31/17,8/1/17,2354,Weapon Law Violations,1,Weapons Law Violations,45.4974,-122.580,7668725.0,674298.0,8/31/17,8/1/17

In [21]:
# verify counts
crime_df.count()

Address              37365
Case Number          41032
Crime Against        41032
Neighborhood         39712
Number of Records    41032
Occur Date           41032
Occur Month Year     41032
Occur Time           41032
Offense Category     41032
Offense Count        41032
Offense Type         41032
Open Data Lat        36712
Open Data Lon        36712
Open Data X          36712
Open Data Y          36712
Report Date          41032
Report Month Year    41032
dtype: int64

In [13]:
# Check to see if there are any values with mispelled or similar values in "Offense Type"
crime_df["Offense Type"].value_counts()

Theft From Motor Vehicle                       7256
All Other Larceny                              4900
Motor Vehicle Theft                            4799
Vandalism                                      4189
Burglary                                       2901
Simple Assault                                 2453
Shoplifting                                    2332
Identity Theft                                 2040
Intimidation                                   1678
Aggravated Assault                             1217
Drug/Narcotic Violations                       1142
Theft of Motor Vehicle Parts or Accessories    1107
False Pretenses/Swindle/Confidence Game         972
Theft From Building                             961
Robbery                                         680
Counterfeiting/Forgery                          470
Weapons Law Violations                          298
Credit Card/ATM Fraud                           264
Rape                                            228
Arson                                           221
Prostitution                                    166
Fondling                                        147
Pocket-Picking                                  107
Purse-Snatching                                  98
Embezzlement                                     78
Stolen Property Offenses                         59
Kidnapping/Abduction                             56
Sodomy                                           51
Hacking/Computer Invasion                        22
Theft From Coin-Operated Machine or Device       20
Animal Cruelty                                   19
Statutory Rape                                   18
Murder and Non-negligent Manslaughter            14
Extortion/Blackmail                              13
Pornography/Obscene Material                     11
Assisting or Promoting Prostitution              11
Sexual Assault With An Object                    10
Drug Equipment Violations                         6
Impersonation                                     6
Wire Fraud                                        4
Involuntary Servitude                             4
Commercial Sex Acts                               2
Incest                                            1
Welfare Fraud                                     1
Name: Offense Type, dtype: int64

In [18]:
# Combine similar offenses
crime_df = crime_df.replace({"Commercial Sex Acts":"Prostitution",
                 "Assisting or Promoting Prostitution":"Prostitution"})

In [19]:
# Check to see if you comnbined similar offenses correctly in "Offense Type".
crime_df["Offense Type"].value_counts()

Theft From Motor Vehicle                       7256
All Other Larceny                              4900
Motor Vehicle Theft                            4799
Vandalism                                      4189
Burglary                                       2901
Simple Assault                                 2453
Shoplifting                                    2332
Identity Theft                                 2040
Intimidation                                   1678
Aggravated Assault                             1217
Drug/Narcotic Violations                       1142
Theft of Motor Vehicle Parts or Accessories    1107
False Pretenses/Swindle/Confidence Game         972
Theft From Building                             961
Robbery                                         680
Counterfeiting/Forgery                          470
Weapons Law Violations                          298
Credit Card/ATM Fraud                           264
Rape                                            228
Arson                                           221
Prostitution                                    179
Fondling                                        147
Pocket-Picking                                  107
Purse-Snatching                                  98
Embezzlement                                     78
Stolen Property Offenses                         59
Kidnapping/Abduction                             56
Sodomy                                           51
Hacking/Computer Invasion                        22
Theft From Coin-Operated Machine or Device       20
Animal Cruelty                                   19
Statutory Rape                                   18
Murder and Non-negligent Manslaughter            14
Extortion/Blackmail                              13
Pornography/Obscene Material                     11
Sexual Assault With An Object                    10
Impersonation                                     6
Drug Equipment Violations                         6
Involuntary Servitude                             4
Wire Fraud                                        4
Incest                                            1
Welfare Fraud                                     1
Name: Offense Type, dtype: int64